### ISSUE TITLE
Unit test failing on 32-bit x86 environment

### ISSUE THREAD

**Issue by aguedes** [AVnu/libavtp#11]
ALSA community folks have reported the unit test is failing on 32-bit x86 environment. Here is a link to the report: http://mailman.alsa-project.org/pipermail/alsa-devel/2018-December/142772.html.

The log shows:
```
[   64s] [  FAILED  ] 4 test(s), listed below:
[   64s] [  FAILED  ] crf_get_field_pull
[   64s] [  FAILED  ] crf_get_field_base_freq
[   64s] [  FAILED  ] crf_set_field_pull
[   64s] [  FAILED  ] crf_set_field_base_freq
```

**Comment by andrew-elder** [comment]
@aguedes - are you in charge of fixing this?

**Comment by aguedes** [comment]
@rjingar is actually looking into this.

**Comment by rjingar** [comment]
Hello, PR has been created to fix this issue.

**Comment by aguedes** [comment]
For reference, this is the PR https://github.com/AVnu/libavtp/pull/12 and it has been merged already so I'm closing this issue. Thanks all!
