### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by dvzrv** [AVnu/libavtp#21]
Hi! I know this repository hasn't been around for super long, but it seems, that libavtp can already be integrated into ALSA and gstreamer.

It would be great, if a release was tagged, so this software could be packaged (I'd like to add it for Arch Linux).

**Comment by aguedes** [comment]
Hi @dvzrv, sure, that make sense. I'll make a release by EOW.

**Comment by aguedes** [comment]
Release published and repository tagged.

https://github.com/AVnu/libavtp/releases
