### ISSUE TITLE
did i can run libavtp with two pc using both i219 and i217 ?? and what is the steps that i need  to run one talker and one listener ?

### ISSUE THREAD

**Issue by ghassenbelghith** [Avnu/libavtp#25]
Hi ,
i'am new  here and i want to run one talker and one listener,  need help 

Thanks

**Comment by aguedes** [comment]
Hi @ghassenbelghith, to run AVB audio or video applications built on top of libavtp, I'd recommend you take a look at https://tsn.readthedocs.io. It provides step-by-step tutorials on how to achieve that.
