### ISSUE TITLE
Need option to disable cmocka

### ISSUE THREAD

**Issue by zeerd** [Avnu/libavtp#26]
Hello!

Mosen.build set the unit-test programs to `build_by_default: false`, but the `test` section made them **must** to be build.

Would you please add something, so that I could ignore them by command line?

I don't know how to modify the meson.build to do this. And there is no cmocka in my target-sdk (for cross-compile).

**Comment by aguedes** [comment]
Hi @zeerd, I believe the issue you're reporting has been already fixed by https://github.com/Avnu/libavtp/pull/24. Make sure you're using that latest 'master' branch.

Feel free to reopen this issue if it still doesn't work for you.
