### ISSUE TITLE
meson build fails - ModuleNotFoundError No module named 'mesonbuild' FAILED: meson-install

### ISSUE THREAD

**Issue by elabbing** [Avnu/libavtp#30]
Hello,
my host:
`Linux ubuntu 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
`meson --version 0.57.1`
`ninja --version 1.10.0`

I run:
```
pip3 install --user meson
sudo apt install ninja-build
```
then I try to install `libavtp` as reportes in `readme.md` file
```
git clone --recursive https://github.com/AVnu/libavtp.git
cd libavtp
meson build
ninja -C build
sudo ninja -C build install
```

but it exits on error at `meson build`
`ModuleNotFoundError No module named 'mesonbuild' FAILED: meson-install`

Then I tried following, with always same error:
```
pip3 install  meson
...
meson build
...
ModuleNotFoundError No module named 'mesonbuild' FAILED: meson-install
```
```
sudo pip3 install meson
...
meson build
...
ModuleNotFoundError No module named 'mesonbuild' FAILED: meson-install
```

Then I tried
```
sudo pip3 install meson
...
sudo meson build
sudo ninja -C build
sudo ninja -C build install
```
This worked about libavtp install.
I think it is a bad workaround, with potential failure about GStreamer.

Any idea?
Many thanks

**Comment by edersondisouza** [comment]
Hi @elabbing,

I kinda think your environment may be messed up by the previous tries to install meson. Have you tried to uninstall all of them? I mean, the one installed without sudo, using `--user` and with sudo. Then installing following https://mesonbuild.com/SimpleStart.html#linux1 or https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip?

**Comment by elabbing** [comment]
Thanks, I retry on a live session and all works.
Now, I will try to fix on the messy system, otherwise I will restart from new installation.

**Comment by edersondisouza** [comment]
I'm assuming the issue was solved, so I'll close this issue.
