### ISSUE TITLE
No such element or plugin 'avtp'

### ISSUE THREAD

**Issue by namdala** [Avnu/libavtp#44]
Hello.

After completing the build to use AVTP, I am unable to find the AVTP element in GStreamer.

$gst-inspect-1.0 avtp
No such element or plugin 'avtp'

No errors occurred during the installation process. and I can find avtp.pc in /usr/local/lib/x86_64-linux-gun/pkgconfig.
Please let me know what went wrong or if there are any specific areas that I need to check.
I have proceeded with the build as follows.

- configuration
   Ubuntu 20.04 
   kernel 5.4
   meson 1.2.1

1. build libavtp
    $git clone https://github.com/Avnu/libavtp
    $ cd libavtp
    $ meson build
    $ ninja -C build
    $ ninja -C build install

2. build Gstreamer
    $git clone https://github.com/GStreamer/gstreamer.git
    $meson build-gst-full \
        --buildtype=release \
        --strip \
        --default-library=static \
        --wrap-mode=forcefallback \
        -Dauto_features=disabled \
        -Dgst-full-libraries=app,video,player \
        -Dbase=enabled \
        -Dgood=enabled \
        -Dbad=enabled \
        -Dgst-plugins-base:typefind=enabled \
        -Dgst-plugins-base:app=enabled \
        -Dgst-plugins-base:playback=enabled \
        -Dgst-plugins-base:volume=enabled \
        **-Dgst-plugins-bad:avtp=enabled \**
        -Dgst-plugins-base:audioconvert=enabled \
        -Dgst-plugins-good:audioparsers=enabled \
        -Dgst-plugins-good:isomp4=enabled \
        -Dgst-plugins-good:deinterlace=enabled \
        -Dgst-plugins-good:audiofx=enabled \
        -Dgst-plugins-bad:videoparsers=enabled
    $ninja -C build-gst-full
    $sudo ninja -C build-gst-full install

Thanks.

**Comment by edersondisouza** [comment]
Hi @namdala,

Could you please share the output of meson and ninja commands for both libavtp and gstreamer? Maybe something went wrong somewhere, and it's kinda hard to find on the huge gstreamer meson output.
