### ISSUE TITLE
Library has unversioned SONAME

### ISSUE THREAD

**Issue by thiagomacieira** [AVnu/libavtp#7]
The commands listed in the README produce a `/usr/lib64/libavtp.so` which has:
```
# readelf -d libavtp.so  | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libavtp.so]
```

Please give it a proper version number and create the necessary symlinks, like any Linux library.

**Comment by aguedes** [comment]
Sure, I'm working on it.

**Comment by thiagomacieira** [comment]
After building, what lib files are created and what SONAME does it have inside?

**Comment by aguedes** [comment]
```
$ ll build/libavtp*
libavtp.so -> libavtp.so.0*
libavtp.so.0 -> libavtp.so.0.1*
libavtp.so.0.1*

$ readelf -d build/libavtp.so.0.1 | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libavtp.so.0]
```

**Comment by aguedes** [comment]
Great! The PR has been merged so I'm closing this issue.
